---
title: "Prediction Assignment"
author: "Mark Wan"
date: "11/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(corrplot)
```

## **Introduction**
***
The goal of this study is to apply machine learning techniques to predict exercise types based on activity data.

## **Load Data**
```{r load data}
#download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv","training.csv")
#download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv","testing.csv")
training <- read.csv('training.csv')
testing <- read.csv('testing.csv')
```

## **Clean Data**
```{r clean data}
cols <- c('user_name','new_window','num_window','classe')
training[cols] <- lapply(training[cols],as.factor)
training$cvtd_timestamp <- ts(training$cvtd_timestamp)
training2 <- subset(training, select=-c(classe))

cols <- c('user_name','new_window','num_window')
testing[cols] <- lapply(testing[cols],as.factor)
testing$cvtd_timestamp <- ts(testing$cvtd_timestamp)
```

## **Feature Selection**
```{r feature selection}
col_num <- character()
for (name in names(training2)){
  if (class(training2[,name])=='numeric') {
    col_num <- append(col_num,name)
  }
}
training2_2 <- training2[col_num]
```

## **Preprocessing**
```{r preprocess}
library(RANN)
preObj <- preProcess(training2,method='knnImpute')
training3 <- predict(preObj,training2)

```

## **Train Model (rf)**
```{r train}
preProc <- preProcess(training3,method='pca',thresh=0.8)
training4 <- predict(preProc,training3)
training5 <- training4[,-nearZeroVar(training4)]
#modelFit <- train(training$classe~.,method='rf',data=training5,preProcess=c('center','scale'))

#modelFit_PCA <- train(training$classe~.,method='rf',preProcess=c('pca','center','scale'),data=training4,trControl=trainControl(preProcOptions = list(thresh=0.8)))

```

svm
lda
gbm
